# Generated by Django 3.1.4 on 2020-12-15 17:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=60, verbose_name='نام نویسنده')),
                ('last_name', models.CharField(max_length=60, verbose_name='فامیل نویسنده')),
                ('DateOfBart', models.DateTimeField(verbose_name='تاریخ تولد')),
                ('DateOfDeath', models.DateTimeField(verbose_name='تاریخ رفات')),
            ],
            options={
                'verbose_name': 'نویسنده',
                'verbose_name_plural': 'نویسنده ها',
                'ordering': ['first_name', 'last_name'],
            },
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=60, verbose_name='عنوان کتاب')),
                ('Summary', models.TextField(max_length=500, verbose_name='توضیحات کتاب ')),
                ('Author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='sportsprogram.author', verbose_name='نویسنده')),
            ],
            options={
                'verbose_name': 'کتاب',
                'verbose_name_plural': 'کتاب ها',
            },
        ),
        migrations.CreateModel(
            name='BookHome',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, verbose_name='کتابخانه')),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, verbose_name='ژانر')),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'ژانر کتاب',
                'verbose_name_plural': 'ژانر کتاب ها',
            },
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, verbose_name='زبان')),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'زبان کتاب',
                'verbose_name_plural': 'زبان کتاب ها',
            },
        ),
        migrations.CreateModel(
            name='BookInstance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, help_text='unique id for this book', primary_key=True, serialize=False)),
                ('imprint', models.CharField(max_length=200)),
                ('file', models.FileField(blank=True, null=True, upload_to='uploads/image/')),
                ('due_back', models.DateField(blank=True, null=True)),
                ('status', models.CharField(blank=True, choices=[('m', 'Maintenance'), ('o', 'on Loan'), ('a', 'Available'), ('r', 'Reserve')], help_text='Book availability', max_length=4)),
                ('book', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='sportsprogram.book')),
                ('borrower', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'جلد کتاب',
                'verbose_name_plural': 'جلد کتاب ها',
                'ordering': ['due_back'],
            },
        ),
        migrations.AddField(
            model_name='book',
            name='Genre',
            field=models.ManyToManyField(to='sportsprogram.Genre', verbose_name='ژانر کتاب'),
        ),
        migrations.AddField(
            model_name='book',
            name='bookHome',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='sportsprogram.bookhome'),
        ),
        migrations.AddField(
            model_name='book',
            name='bookparent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='sportsprogram.book'),
        ),
    ]
