# Generated by Django 3.1.4 on 2020-12-15 17:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sportsprogram', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='Author',
        ),
        migrations.RemoveField(
            model_name='book',
            name='Genre',
        ),
        migrations.RemoveField(
            model_name='book',
            name='bookHome',
        ),
        migrations.RemoveField(
            model_name='book',
            name='bookparent',
        ),
        migrations.RemoveField(
            model_name='bookinstance',
            name='book',
        ),
        migrations.RemoveField(
            model_name='bookinstance',
            name='borrower',
        ),
        migrations.DeleteModel(
            name='Language',
        ),
        migrations.DeleteModel(
            name='Author',
        ),
        migrations.DeleteModel(
            name='Book',
        ),
        migrations.DeleteModel(
            name='BookHome',
        ),
        migrations.DeleteModel(
            name='BookInstance',
        ),
        migrations.DeleteModel(
            name='Genre',
        ),
    ]
