# Generated by Django 3.1.4 on 2020-12-15 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sportsprogram', '0002_auto_20201215_2124'),
    ]

    operations = [
        migrations.CreateModel(
            name='personInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FirstName', models.CharField(max_length=50, verbose_name='نام')),
                ('LastName', models.CharField(max_length=50, verbose_name='نام خانوادگی')),
                ('FatherName', models.CharField(max_length=50, verbose_name='نام پدر')),
                ('Sex', models.CharField(choices=[('m', 'مرد'), ('f', 'خانم')], default='m', max_length=1, verbose_name='جنسیت')),
                ('DateOfBart', models.DateTimeField(verbose_name='تاریخ تولد')),
                ('bloodType', models.CharField(choices=[('a+', 'a+'), ('a-', 'a-'), ('b+', 'b+'), ('b-', 'b-'), ('ab+', 'ab+'), ('ab-', 'ab-'), ('o+', 'o+'), ('o-', 'o-')], default='a', max_length=3, verbose_name='گروه خونی')),
                ('NationalCode', models.IntegerField(verbose_name='کد ملی')),
                ('ShenasnameCode', models.IntegerField(verbose_name='شماره شناسنامه')),
                ('MohaleSedor', models.IntegerField(verbose_name='محل صدور')),
                ('VazyateTahol', models.CharField(choices=[('s', 'مجرد'), ('m', 'متاهل')], default='s', max_length=1, verbose_name='وضعیت تاهل ')),
                ('Nesbat', models.CharField(choices=[('k', 'خودم'), ('h', 'همسرم'), ('f', 'فرزندم'), ('t', 'تحت تکلفم')], default='k', help_text='نسبت شما به شخص کارمند', max_length=1, verbose_name='نسبت')),
                ('Tahsilat', models.CharField(choices=[('m', 'محصل'), ('d', 'دیپلم و زیر دیپلم'), ('l', 'لیسانس'), ('f', 'فوق لیسانس'), ('d', 'دکترا')], default='m', help_text='تحصیلات شما', max_length=1, verbose_name='تحصیلات')),
                ('Address', models.TextField(max_length=300, verbose_name='آدرس کامل')),
                ('phoneNumber', models.IntegerField(verbose_name='شماره همراه')),
                ('WorkNumber', models.IntegerField(blank=True, verbose_name='شماره محل کار')),
                ('HomeNumber', models.IntegerField(blank=True, verbose_name='شماره منزل')),
                ('SabegheVarzeshi', models.CharField(max_length=50, verbose_name='سابقه ورزشی')),
                ('Height', models.IntegerField(verbose_name='قد')),
                ('Weight', models.IntegerField(verbose_name='وزن')),
                ('DaroyeKhas', models.TextField(max_length=200, verbose_name='مصرف دارو')),
                ('SabegehBimari', models.TextField(max_length=200, null=True, verbose_name='سلبقع بیماری')),
                ('Paradox', models.TextField(max_length=200, null=True, verbose_name='ناهنجاری')),
            ],
        ),
    ]
