# Generated by Django 3.1.4 on 2020-12-15 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sportsprogram', '0003_personinfo'),
    ]

    operations = [
        migrations.AddField(
            model_name='personinfo',
            name='Mojtame',
            field=models.CharField(blank=True, choices=[('s', 'سرچشمه'), ('b', 'شهربابک'), ('o', 'سوسنگرد')], help_text='محل کارا', max_length=1, verbose_name='مجتمع'),
        ),
        migrations.AddField(
            model_name='personinfo',
            name='Omor',
            field=models.CharField(blank=True, max_length=10, verbose_name='امور'),
        ),
        migrations.AddField(
            model_name='personinfo',
            name='PersonelNo',
            field=models.IntegerField(blank=True, default=123, verbose_name='شماره پرسنلی'),
        ),
        migrations.AddField(
            model_name='personinfo',
            name='Semat',
            field=models.CharField(blank=True, choices=[('m', 'مدیر'), ('o', 'معاون'), ('s', 'سرپرست'), ('k', 'کارشناس')], help_text='سمت شغلی', max_length=1, verbose_name='سمت'),
        ),
    ]
