# Generated by Django 3.1.4 on 2020-12-15 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sportsprogram', '0004_auto_20201215_2243'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personinfo',
            name='PersonelNo',
            field=models.IntegerField(blank=True, verbose_name='شماره پرسنلی'),
        ),
    ]
