# Generated by Django 3.1.4 on 2020-12-16 09:28

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('sportsprogram', '0005_auto_20201215_2243'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personinfo',
            name='HomeNumber',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, region=None, verbose_name='شماره منزل'),
        ),
        migrations.AlterField(
            model_name='personinfo',
            name='PersonelNo',
            field=models.IntegerField(blank=True, help_text='شماره پرسنی خود و یا شخص کارمند', verbose_name='شماره پرسنلی'),
        ),
        migrations.AlterField(
            model_name='personinfo',
            name='SabegehBimari',
            field=models.TextField(max_length=200, null=True, verbose_name='سابقه بیماری'),
        ),
        migrations.AlterField(
            model_name='personinfo',
            name='WorkNumber',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, region=None, verbose_name='شماره محل کار'),
        ),
        migrations.AlterField(
            model_name='personinfo',
            name='phoneNumber',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, verbose_name='شماره همراه'),
        ),
    ]
