# Generated by Django 3.1.4 on 2020-12-16 10:55

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sportsprogram', '0006_auto_20201216_1258'),
    ]

    operations = [
        migrations.AddField(
            model_name='personinfo',
            name='BMI',
            field=models.CharField(blank=True, choices=[('n', 'پایین'), ('l', 'نرمال'), ('u', 'بالا'), ('h', 'بسیار بالا')], max_length=1, verbose_name='شاخص توده بدنی'),
        ),
        migrations.AddField(
            model_name='personinfo',
            name='BMR',
            field=models.IntegerField(null=True, verbose_name='کالری پایه'),
        ),
        migrations.AddField(
            model_name='personinfo',
            name='BodyFat_a',
            field=models.CharField(blank=True, choices=[('n', 'پایین'), ('l', 'نرمال'), ('u', 'بالا')], max_length=1, verbose_name='میزان جاقی دست ها'),
        ),
        migrations.AddField(
            model_name='personinfo',
            name='BodyFat_l',
            field=models.CharField(blank=True, choices=[('n', 'پایین'), ('l', 'نرمال'), ('u', 'بالا')], max_length=1, verbose_name='میزان جاقی پاها'),
        ),
        migrations.AddField(
            model_name='personinfo',
            name='BodyFat_t',
            field=models.CharField(blank=True, choices=[('n', 'پایین'), ('l', 'نرمال'), ('u', 'بالا')], max_length=1, verbose_name='میزان جاقی تنه'),
        ),
        migrations.AddField(
            model_name='personinfo',
            name='BodyFat_w',
            field=models.CharField(blank=True, choices=[('n', 'پایین'), ('l', 'نرمال'), ('u', 'بالا'), ('h', 'بسیار بالا')], max_length=1, verbose_name='میزان جاقی کل بدن'),
        ),
        migrations.AddField(
            model_name='personinfo',
            name='Bodyweight',
            field=models.IntegerField(null=True, verbose_name='وزن بدن با دستگاه'),
        ),
        migrations.AddField(
            model_name='personinfo',
            name='Bone',
            field=models.IntegerField(null=True, verbose_name='استخوان'),
        ),
        migrations.AddField(
            model_name='personinfo',
            name='Bwater',
            field=models.CharField(blank=True, choices=[('n', 'پایین'), ('l', 'نرمال'), ('u', 'بالا')], max_length=1, verbose_name='شاخص توده بدنی'),
        ),
        migrations.AddField(
            model_name='personinfo',
            name='Compo_date',
            field=models.DateField(auto_now_add=True, null=True, verbose_name='تاریخ تست گرفتن'),
        ),
        migrations.AddField(
            model_name='personinfo',
            name='LV',
            field=models.CharField(blank=True, choices=[('l', 'نرمال'), ('u', 'بالا')], max_length=1, verbose_name='چربی احشایی'),
        ),
        migrations.AddField(
            model_name='personinfo',
            name='Mage',
            field=models.IntegerField(null=True, verbose_name='سن متابولیک'),
        ),
        migrations.AddField(
            model_name='personinfo',
            name='MusclQuality_a',
            field=models.CharField(blank=True, choices=[('n', 'پایین'), ('l', 'نرمال'), ('u', 'بالا')], max_length=1, verbose_name='کیفیت عضله دست ها'),
        ),
        migrations.AddField(
            model_name='personinfo',
            name='MusclQuality_l',
            field=models.CharField(blank=True, choices=[('n', 'پایین'), ('l', 'نرمال'), ('u', 'بالا')], max_length=1, verbose_name='کیفیت عضله پاها'),
        ),
        migrations.AddField(
            model_name='personinfo',
            name='MusclQuality_w',
            field=models.CharField(blank=True, choices=[('n', 'پایین'), ('l', 'نرمال'), ('u', 'بالا'), ('h', 'بسیار بالا')], max_length=1, verbose_name='کیفیت عضله کل بدن'),
        ),
        migrations.AddField(
            model_name='personinfo',
            name='MuscleMass_a',
            field=models.CharField(blank=True, choices=[('n', 'پایین'), ('l', 'نرمال'), ('u', 'بالا')], max_length=1, verbose_name='میزان عضله دست ها'),
        ),
        migrations.AddField(
            model_name='personinfo',
            name='MuscleMass_l',
            field=models.CharField(blank=True, choices=[('n', 'پایین'), ('l', 'نرمال'), ('u', 'بالا')], max_length=1, verbose_name='میزان عضله پاها'),
        ),
        migrations.AddField(
            model_name='personinfo',
            name='MuscleMass_t',
            field=models.CharField(blank=True, choices=[('n', 'پایین'), ('l', 'نرمال'), ('u', 'بالا')], max_length=1, verbose_name='میزان عضله تنه'),
        ),
        migrations.AddField(
            model_name='personinfo',
            name='MuscleMass_w',
            field=models.CharField(blank=True, choices=[('n', 'پایین'), ('l', 'نرمال'), ('u', 'بالا'), ('h', 'بسیار بالا')], max_length=1, verbose_name='میزان عضله کل بدن'),
        ),
        migrations.AlterField(
            model_name='personinfo',
            name='DateOfBart',
            field=models.DateField(verbose_name='تاریخ تولد'),
        ),
        migrations.AlterField(
            model_name='personinfo',
            name='HomeNumber',
            field=models.CharField(blank=True, max_length=11, validators=[django.core.validators.RegexValidator(message='شماره وارد شده صحیح نمیباشد', regex='^\\+?0?\\d{8,11}$')], verbose_name='شماره منزل'),
        ),
        migrations.AlterField(
            model_name='personinfo',
            name='WorkNumber',
            field=models.CharField(blank=True, max_length=11, validators=[django.core.validators.RegexValidator(message='شماره وارد شده صحیح نمیباشد', regex='^\\+?0?\\d{8,11}$')], verbose_name='شماره محل کار'),
        ),
        migrations.AlterField(
            model_name='personinfo',
            name='phoneNumber',
            field=models.CharField(blank=True, max_length=11, validators=[django.core.validators.RegexValidator(message='شماره وارد شده صحیح نمیباشد', regex='^\\+?0?\\d{8,11}$')], verbose_name='شماره همراه'),
        ),
    ]
