# Generated by Django 3.1.4 on 2020-12-16 11:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sportsprogram', '0007_auto_20201216_1425'),
    ]

    operations = [
        migrations.RenameField(
            model_name='personinfo',
            old_name='MusclQuality_a',
            new_name='MuscleQuality_a',
        ),
        migrations.RenameField(
            model_name='personinfo',
            old_name='MusclQuality_l',
            new_name='MuscleQuality_l',
        ),
        migrations.RenameField(
            model_name='personinfo',
            old_name='MusclQuality_w',
            new_name='MuscleQuality_w',
        ),
    ]
