# Generated by Django 3.1.4 on 2020-12-16 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sportsprogram', '0008_auto_20201216_1434'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExerciseGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, verbose_name='نام عضله')),
                ('description', models.TextField(max_length=200, null=True, verbose_name='توضیحات عضله')),
            ],
        ),
        migrations.AlterField(
            model_name='personinfo',
            name='Bwater',
            field=models.CharField(blank=True, choices=[('n', 'پایین'), ('l', 'نرمال'), ('u', 'بالا')], max_length=1, verbose_name='آب بدن'),
        ),
        migrations.AlterField(
            model_name='personinfo',
            name='Compo_date',
            field=models.DateField(verbose_name='تاریخ تست گرفتن'),
        ),
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=60, verbose_name='عنوان حرکت')),
                ('description', models.TextField(max_length=200, null=True, verbose_name='توضیحات حرکت')),
                ('ExerciseGroups', models.ManyToManyField(to='sportsprogram.ExerciseGroup')),
            ],
        ),
    ]
