# Generated by Django 3.1.4 on 2020-12-16 14:38

from django.db import migrations, models
import sportsprogram.models


class Migration(migrations.Migration):

    dependencies = [
        ('sportsprogram', '0010_auto_20201216_1726'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise',
            name='video',
            field=models.FileField(null=True, upload_to='media/videos/exercise/', validators=[sportsprogram.models.validate_file_extension], verbose_name='ویدو حرکت'),
        ),
    ]
