# Generated by Django 3.1.4 on 2020-12-16 16:31

from django.db import migrations, models
import django.db.models.deletion
import sportsprogram.models


class Migration(migrations.Migration):

    dependencies = [
        ('sportsprogram', '0011_exercise_video'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='exercise',
            options={'verbose_name': 'حرکت', 'verbose_name_plural': 'حرکت ها'},
        ),
        migrations.AlterModelOptions(
            name='exercisegroup',
            options={'verbose_name': 'عضله', 'verbose_name_plural': 'عضله ها'},
        ),
        migrations.AlterModelOptions(
            name='personinfo',
            options={'verbose_name': 'کاربر', 'verbose_name_plural': 'کاربرها'},
        ),
        migrations.AddField(
            model_name='exercise',
            name='pdf',
            field=models.FileField(null=True, upload_to='media/pdf/exercise/', validators=[sportsprogram.models.validate_file_pdf], verbose_name='برنامه غذایی'),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='ExerciseGroups',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='sportsprogram.exercisegroup', verbose_name='عضله'),
        ),
        migrations.CreateModel(
            name='PersonExercise',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ZamanEsterahat', models.IntegerField(verbose_name='زمان استراحت')),
                ('TedadSet', models.IntegerField(verbose_name='تعداد ست')),
                ('TedadTekrar', models.IntegerField(verbose_name='تعداد تکرار')),
                ('ShomareHarkat', models.IntegerField(verbose_name='شماره حرکت')),
                ('DateWeek', models.CharField(blank=True, choices=[('s', 'شنبه'), ('y', 'یک شنبه'), ('d', 'دو شنبه'), ('s', 'سه شنبه'), ('c', 'چهار شنبه'), ('p', 'پنج شنبه'), ('g', 'جمعه')], max_length=6, verbose_name='روز هفته')),
                ('Exercise', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='sportsprogram.exercise', verbose_name='حرکت ورزشی')),
                ('PersonInfo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='sportsprogram.personinfo', verbose_name='شخص وزش کار')),
            ],
            options={
                'verbose_name': 'برنامه ورزشی فردی',
                'verbose_name_plural': 'برنامه ورزشی فردی',
            },
        ),
    ]
