# Generated by Django 3.1.4 on 2020-12-17 08:17

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('sportsprogram', '0012_auto_20201216_2001'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personexercise',
            name='DateWeek',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('s', 'شنبه'), ('y', 'یک شنبه'), ('d', 'دو شنبه'), ('s', 'سه شنبه'), ('c', 'چهار شنبه'), ('p', 'پنج شنبه'), ('g', 'جمعه')], max_length=3),
        ),
    ]
