# Generated by Django 3.1.4 on 2020-12-17 10:48

import datetime
from django.db import migrations, models
import django.db.models.deletion
import multiselectfield.db.fields
import sportsprogram.models


class Migration(migrations.Migration):

    dependencies = [
        ('sportsprogram', '0013_auto_20201217_1147'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exercise',
            name='pdf',
        ),
        migrations.AlterField(
            model_name='personexercise',
            name='DateWeek',
            field=multiselectfield.db.fields.MultiSelectField(choices=[(0, 'شنبه'), (1, 'یک شنبه'), (2, 'دو شنبه'), (3, 'سه شنبه'), (4, 'چهار شنبه'), (5, 'پنج شنبه'), (6, 'جمعه')], default=(0, 3), max_length=7, verbose_name='روز های تکرار'),
        ),
        migrations.CreateModel(
            name='FoodPrograming',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pdf', models.FileField(null=True, upload_to='media/pdf/exercise/', validators=[sportsprogram.models.validate_file_pdf], verbose_name='برنامه غذایی')),
                ('FoodDate', models.DateField(default=datetime.date.today, verbose_name='تاریخ برنامه')),
                ('PersonInfo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='sportsprogram.personinfo', verbose_name='شخص وزش کار')),
            ],
        ),
    ]
