# Generated by Django 3.1.4 on 2020-12-18 08:08

from django.db import migrations, models
import django.db.models.deletion
import sportsprogram.models


class Migration(migrations.Migration):

    dependencies = [
        ('sportsprogram', '0014_auto_20201217_1418'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='foodprograming',
            options={'verbose_name': 'برنامه غذایی', 'verbose_name_plural': 'برنامه های غذایی'},
        ),
        migrations.AlterField(
            model_name='foodprograming',
            name='pdf',
            field=models.FileField(null=True, upload_to='media/pdf/exercise/', validators=[sportsprogram.models.validate_file_pdf], verbose_name='فایل برنامه غذایی'),
        ),
        migrations.AlterField(
            model_name='personexercise',
            name='Exercise',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='sportsprogram.exercise', verbose_name='حرکت ورزشی'),
        ),
        migrations.AlterField(
            model_name='personexercise',
            name='PersonInfo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='sportsprogram.personinfo', verbose_name='شخص وزش کار'),
        ),
        migrations.AlterField(
            model_name='personexercise',
            name='ShomareHarkat',
            field=models.IntegerField(default=1, verbose_name='شماره حرکت'),
        ),
        migrations.AlterField(
            model_name='personexercise',
            name='TedadSet',
            field=models.IntegerField(default=3, verbose_name='تعداد ست'),
        ),
        migrations.AlterField(
            model_name='personexercise',
            name='TedadTekrar',
            field=models.IntegerField(default=7, verbose_name='تعداد تکرار'),
        ),
        migrations.AlterField(
            model_name='personexercise',
            name='ZamanEsterahat',
            field=models.IntegerField(default=30, help_text='زمان استراحت', verbose_name='زمان استراحت'),
        ),
    ]
