# Generated by Django 3.1.4 on 2020-12-19 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sportsprogram', '0015_auto_20201218_1138'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise',
            name='Token',
            field=models.CharField(default='TbIRr8OTDOO6f98ljkd1cdZq6BocdaMf', max_length=32),
        ),
    ]
