# Generated by Django 3.1.4 on 2020-12-19 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sportsprogram', '0017_auto_20201219_1343'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personinfo',
            name='Token',
            field=models.CharField(auto_created=True, default='Ta6B2yLpNY0XIrUoG0R6RH4u2kDIdmI4x2gv7vp45epYGxL9FDff5ZchxUFFRelZ', max_length=64),
        ),
    ]
