# Generated by Django 3.1.4 on 2020-12-19 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sportsprogram', '0018_auto_20201219_1345'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personinfo',
            name='Token',
        ),
        migrations.AddField(
            model_name='personinfo',
            name='ApiToken',
            field=models.CharField(auto_created=True, default='h8XBlHZxCUjFCvtEcsRcs0Y2sJKOYyGdayHMOa3JGCxjetEz4EG4gI4tut03nMOr', max_length=64),
        ),
    ]
