# Generated by Django 3.1.4 on 2020-12-19 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sportsprogram', '0020_auto_20201219_1753'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personinfo',
            name='ApiToken',
            field=models.CharField(auto_created=True, default='13j8qXJTdhkApwbNNpWIjziA0RIIbB6syu0gQt24HRP1OofGxTS1pnSNsUGSt0o4', max_length=64, unique=True),
        ),
        migrations.AlterField(
            model_name='personinfo',
            name='Password',
            field=models.CharField(max_length=50, verbose_name='رمز ورود'),
        ),
        migrations.AlterField(
            model_name='personinfo',
            name='Username',
            field=models.CharField(max_length=50, unique=True, verbose_name='نام کاربری'),
        ),
    ]
