# Generated by Django 3.1.4 on 2020-12-25 11:56

from django.db import migrations, models
import django_jalali.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('sportsprogram', '0022_auto_20201225_1152'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personinfo',
            name='ApiToken',
            field=models.CharField(auto_created=True, default='zYSxbrpD2MNnlJFqViC6PP8MRryQ2gRadQ0wjHlPIUk0ISrWogyxpEmUw9SmPsvj', max_length=64, unique=True),
        ),
        migrations.AlterField(
            model_name='personinfo',
            name='DateOfBart',
            field=django_jalali.db.models.jDateField(verbose_name='تاریخ تولد'),
        ),
    ]
